### ISSUE TITLE
Camera crash

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel-app#69]
```
E/AndroidRuntime( 6751): Process: com.example.curbwheel_flutter, PID: 6751
E/AndroidRuntime( 6751): java.lang.NullPointerException: Attempt to invoke virtual method 'int io.flutter.embedding.engine.systemchannels.PlatformChannel$DeviceOrientation.ordinal()' on a null object reference
E/AndroidRuntime( 6751): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:58)
E/AndroidRuntime( 6751): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:53)
E/AndroidRuntime( 6751): 	at io.flutter.plugins.camera.Camera.runPictureCapture(Camera.java:552)
E/AndroidRuntime( 6751): 	at io.flutter.plugins.camera.Camera.access$1500(Camera.java:73)
E/AndroidRuntime( 6751): 	at io.flutter.plugins.camera.Camera$3.processCapture(Camera.java:510)
E/AndroidRuntime( 6751): 	at io.flutter.plugins.camera.Camera$3.onCaptureCompleted(Camera.java:442)
E/AndroidRuntime( 6751): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureCompleted$3(CameraCaptureSessionImpl.java:640)
E/AndroidRuntime( 6751): 	at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$OA1Yz_YgzMO8qcV8esRjyt7ykp4.run(Unknown Source:8)
E/AndroidRuntime( 6751): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 6751): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6751): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6751): 	at android.app.ActivityThread.main(ActivityThread.java:6865)
E/AndroidRuntime( 6751): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6751): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
E/AndroidRuntime( 6751): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Stack trace
```
_CompileTimeError: Unimplemented handling of missing static target
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 285, col 7, in _BufferingStreamSubscription._add
  File "stream_controller.dart", line 808, col 19, in _SyncStreamControllerDispatch._sendData
  File "stream_controller.dart", line 682, col 7, in _StreamController._add
  File "stream_controller.dart", line 624, col 5, in _StreamController.add
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 285, col 7, in _BufferingStreamSubscription._add
  File "stream_pipe.dart", line 127, col 11, in _ForwardingStreamSubscription._add
  File "stream_pipe.dart", line 224, col 10, in _MapStream._handleData
  File "stream_pipe.dart", line 157, col 13, in _ForwardingStreamSubscription._handleData
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 285, col 7, in _BufferingStreamSubscription._add
  File "stream_pipe.dart", line 127, col 11, in _ForwardingStreamSubscription._add
  File "stream_pipe.dart", line 224, col 10, in _MapStream._handleData
  File "stream_pipe.dart", line 157, col 13, in _ForwardingStreamSubscription._handleData
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 285, col 7, in _BufferingStreamSubscription._add
  File "stream_pipe.dart", line 127, col 11, in _ForwardingStreamSubscription._add
  File "stream_pipe.dart", line 199, col 12, in _WhereStream._handleData
  File "stream_pipe.dart", line 157, col 13, in _ForwardingStreamSubscription._handleData
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 285, col 7, in _BufferingStreamSubscription._add
  File "stream_pipe.dart", line 127, col 11, in _ForwardingStreamSubscription._add
  File "stream_pipe.dart", line 224, col 10, in _MapStream._handleData
  File "stream_pipe.dart", line 157, col 13, in _ForwardingStreamSubscription._handleData
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 285, col 7, in _BufferingStreamSubscription._add
  File "stream_pipe.dart", line 127, col 11, in _ForwardingStreamSubscription._add
  File "stream_pipe.dart", line 199, col 12, in _WhereStream._handleData
  File "stream_pipe.dart", line 157, col 13, in _ForwardingStreamSubscription._handleData
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 285, col 7, in _BufferingStreamSubscription._add
  File "stream_pipe.dart", line 127, col 11, in _ForwardingStreamSubscription._add
  File "stream_pipe.dart", line 224, col 10, in _MapStream._handleData
  File "stream_pipe.dart", line 157, col 13, in _ForwardingStreamSubscription._handleData
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 285, col 7, in _BufferingStreamSubscription._add
  File "stream_pipe.dart", line 127, col 11, in _ForwardingStreamSubscription._add
  File "stream_pipe.dart", line 224, col 10, in _MapStream._handleData
  File "stream_pipe.dart", line 157, col 13, in _ForwardingStreamSubscription._handleData
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 285, col 7, in _BufferingStreamSubscription._add
  File "stream_pipe.dart", line 127, col 11, in _ForwardingStreamSubscription._add
  File "stream_pipe.dart", line 199, col 12, in _WhereStream._handleData
  File "stream_pipe.dart", line 157, col 13, in _ForwardingStreamSubscription._handleData
  File "zone.dart", line 1198, col 47, in _rootRunUnary
  File "zone.dart", line 1100, col 19, in _CustomZone.runUnary
  File "zone.dart", line 1005, col 7, in _CustomZone.runUnaryGuarded
  File "stream_impl.dart", line 357, col 11, in _BufferingStreamSubscription._sendData
  File "stream_impl.dart", line 611, col 14, in _DelayedData.perform
  File "stream_impl.dart", line 730, col 11, in _StreamImplEvents.handleNext
  File "stream_impl.dart", line 687, col 7, in _PendingEvents.schedule.<fn>
  File "zone.dart", line 1182, col 47, in _rootRun
  File "zone.dart", line 1093, col 19, in _CustomZone.run
  File "zone.dart", line 997, col 7, in _CustomZone.runGuarded
  File "zone.dart", line 1037, col 23, in _CustomZone.bindCallbackGuarded.<fn>
  File "zone.dart", line 1190, col 13, in _rootRun
  File "zone.dart", line 1093, col 19, in _CustomZone.run
  File "zone.dart", line 997, col 7, in _CustomZone.runGuarded
  File "zone.dart", line 1037, col 23, in _CustomZone.bindCallbackGuarded.<fn>
  File "schedule_microtask.dart", line 41, col 21, in _microtaskLoop
  File "schedule_microtask.dart", line 50, col 5, in _startMicrotaskLoop
```

**Comment by russbiggs** [comment]
closing for now not reproducing lately
